### PR TITLE
Ts2

### PR DESCRIPTION
**Pull request by chrk623**

### CODE REVIEW

**Comment by chrk623** [comment]
Opening PR for discussion. Will not merge.

**Comment by chrk623** [comment]
@tmelliott here is the PR. Still some todos:
- Make it work with legacy, some common variable/ui names, and not I'm sure if there are any common class names between 2.0 and legacy, or else ill need to `iNZightTS::` everything to make sure it won't break.
- conditional ui on different settings, i.e., no plot setting when plot type = forecast

**Comment by tmelliott** [comment]
For the new vs legacy, just prefix all functions with `iNZightTS::` or `iNZightTSLegacy::`, instead of using a `library()` call. I prefer this anyway as it makes it a lot easier to debug in future.

Let me know if you need help looking into conditional UI stuff - I'm only vaguely aware of how that works though.

**Comment by tmelliott** [comment]
Going to close and re-open in the hopes it triggers a railway build...

**Pull request closed without merging**
