### PR TITLE
Ts2

### LINKED ISSUE #323: New Time Series module
Using [iNZightTS](https://github.com/iNZightVIT/iNZightTS) and based off [the new time series module](https://github.com/iNZightVIT/inzight-time-series-mod) update the Time Series module in Lite, either:

1. (preferred) create an alternate module, so *both* versions can be accessed by users, or
2. replace existing with new.

### PR DESCRIPTION
**Pull request by tmelliott**
Closes #323

### CODE REVIEW

**Comment by tmelliott** [comment]
@chrk623 railway deployment now up and running for this PR - I checked and forecasts working now; can you confirm that the `log_if` issue has gone?

**Comment by chrk623** [comment]
> @chrk623 railway deployment now up and running for this PR - I checked and forecasts working now; can you confirm that the `log_if` issue has gone?

```r
packageVersion("iNZightTS")
# [1] ‘2.0.1’
```

Wierd, I'm still getting `Error in get("log_if") : object 'log_if' not found` locally, but forecast seems to work on the new railway deployment, but decompose and seasonal is now broken. Looking at the logs, it seems like the error is from rendering the plots.

Locally, decompose and seasonal still works, can't seem to reproduce above.

In docker dev container, all 3 of decompose, seasonal and forecast don't work.

Don't know where to start 😂

**Comment by tmelliott** [comment]
Huh, strange...
If you make any headway (forward or back..) let me know, otherwise I'll take a look sometime this or next week..

**Comment by tmelliott** [comment]
@chrk623 
Docker is running R 4.2, updating that might be easy but I need to remind myself precisely which other iNZight* packages don't work on R >= 4.3 (I'm pretty sure it's only the GUI package, though...). 

In local docker, are you able to see the warnings/errors? On railway I'm seeing:
```bash
Warning: Error in Ops.data.frame: ‘==’ only defined for equally-sized data frames
180: stop
179: Ops.data.frame
177: add_guides
176: plot_table.ggplot
174: lapply
173: build_patchwork
172: print.patchwork
167: func
165: f
164: Reduce
155: do
154: hybrid_chain
126: drawPlot
112: <reactive:plotObj>
96: drawReactive
83: renderFunc
82: output$tsui_ts_plot
1: runApp
```

**Comment by chrk623** [comment]
I actually tried other versions the other day but the image wouldnt build, cant remember which versions or what caused the problem though.

I will go at it again this afternoon.

**Comment by chrk623** [comment]
@tmelliott long reply incoming...

I think anything related to the maps module will also cause problems building R >= 4.3.

---

I'm not getting `Warning: Error in Ops.data.frame: ‘==’ only defined for equally-sized data frames` locally, I'm on
```
R version 4.4.1 (2024-06-14)
Platform: x86_64-pc-linux-gnu
Running under: Arch Linux
```
In fact, decompose and seasonal works locally, just not forecast.

From what I can tell its from [this](https://github.com/iNZightVIT/iNZightTS/blob/9626272ec27f1afc5987d6b87efb50a35dfbf759/R/decomposition.R#L423) line,
```R
pdata + pseason + presid + plot_layout(ncol = 1, heights = ratios)
# Error in Ops.data.frame(guide_loc, panel_loc) :   ‘==’ only defined for equally-sized data frames
``` 

---

Still getting `Error in get("log_if") : object 'log_if' not found` with
```R
# remotes::install_github("iNZightVIT/iNZightTS@hotfix/2.0.1")

packageVersion("iNZightTS")
# [1] ‘2.0.1’
```

Could you please confirm if this works on your end?  [ts_p.csv](https://github.com/user-attachments/files/16386724/ts_p.csv) (renamed to `csv`, github won't let me upload `rds`)

```R
ts_p = readRDS("ts_p.csv")

iNZightTS:::predict.inz_ts(
  object = ts_p,
  var = "Arctic",
  model_range = as.Date(c("1990-01-01", "2011-03-01")),
  mult_fit = FALSE
)
```

**I think it worked previously because i forgot to comment out `library(iNZightTS)`**. The new deployment's forecast is not working anymore.

---

Behavior I'm seeing:
- Local:
  - default: ✅  works
  - decompose: ✅ works
  - seasonal: ✅ works
  - forecast: ❌ don't work `Error in get("log_if") : object 'log_if' not found`
- Railway:
  - default: ✅ works
  - decompose: ❌ don't work `Error in Ops.data.frame(guide_loc, panel_loc) :   ‘==’ only defined for equally-sized data frames`
  - seasonal: ❌ don't work `Error in Ops.data.frame(guide_loc, panel_loc) :   ‘==’ only defined for equally-sized data frames`
  - forecast: ❗ Not anymore. Worked in the previous deployment, probably becuase i forgot to comment out `library(iNZightTS)`?
 - Docker dev (`rocker/shiny-verse:4.2`):
    - default: ✅ works
    - decompose: ❌ don't work `Error in Ops.data.frame(guide_loc, panel_loc) :   ‘==’ only defined for equally-sized data frames`
    - seasonal: ❌ don't work `Error in Ops.data.frame(guide_loc, panel_loc) :   ‘==’ only defined for equally-sized data frames`
    - forecast: ❌ don't work `Error in get("log_if") : object 'log_if' not found`


I think maybe the easiest way is to fix `log_if` and get docker to build on 4.2+?

**Comment by tmelliott** [comment]
Thanks @chrk623.
I did some searching and it looks like the `==` bug is from changes in 'ggplot2' affecting 'patchwork', which apparently was fixed? https://github.com/tidyverse/ggplot2/issues/5612 

I'll look more into the `log_if()` issue - I thought prefixing it would solve the problem, unless there's some odd caching going on??

**Comment by tmelliott** [comment]
Seems `install2.r` grabs from an archive, so wasn't fetching the latest versions of everything... attempting to set up a new install method using [pak](https://pak.r-lib.org/index.html)...

**Comment by tmelliott** [comment]
Okay so now it seems to all be working except the forecast plot - but it's a different error now :laughing: :sob: 
"Unable to create temporal object. Maybe you forgot to specify the key" but this has never been an issue before??

**Comment by chrk623** [comment]
> Okay so now it seems to all be working except the forecast plot - but it's a different error now 😆 😭 "Unable to create temporal object. Maybe you forgot to specify the key" but this has never been an issue before??

`"Unable to create temporal object. Maybe you forgot to specify the keys?"` is due to `log_if`. The forecast plot is wrapped within a  `tryCatch`.

**Comment by tmelliott** [comment]
Okay seems it is a bug in ['fabletools'](https://github.com/tidyverts/fabletools/issues/311) that hasn't been fixed, so we'll just put `log_if()` in the global environment as a ~~temporary~~ fix.

**Comment by tmelliott** [comment]
(sorry about the formatting, VSCode does it automatically and I forgot to disable it)

**Comment by tmelliott** [comment]
Right ... looks like it's working. @chrk623 can you do a bunch of testing, please? I've completely changed how the dependencies are installed, so there's a good chance I've missed some.. there are a lot of packages in `functions.R` but I think most of these are deprecated? I think a new issue/PR for tidying up all that is required...

**Comment by chrk623** [comment]
Deployment seems to be working. Pending merge.. Will work on #373.

**Pull request merged**
