### PR TITLE
Features/dataset name

### LINKED ISSUE #291: Show dataset name

### PR DESCRIPTION
**Pull request by chrk623**
Fixes #291

In visualize tab, show:
- `Dataset: {data_name}` for `rda`, `rdta` and other file fomats.
- `Dataset: {data_name}, Sheet: {sheet_name}` for `xls` and `xlsx`.

### CODE REVIEW

**Comment by chrk623** [comment]
@tmelliott you think the font looks OK?

**Comment by tmelliott** [comment]
I'm getting some errors.

Using Example data > census at school - I presume example data isn't setting `data_info` in a way that the data name is expecting?

**Error: An error has occurred. Check your logs or contact the app author for clarification.**

Logs:
```
The `name` provided ('refresh') is deprecated in Font Awesome 5:
* please consider using 'sync' or 'fas fa-sync' instead
* use the `verify_fa = FALSE` to deactivate these messages
Warning: Error in if: argument is of length zero
  97: renderText
  96: func
  83: renderFunc
  82: output$data_info
   1: runApp
```

Import from a file, it's fine - perhaps the font could be smaller? I don't think it needs to draw users' attention, merely it's there as a reminder.

**Comment by chrk623** [comment]
- Use `isTRUE` to check condition to prevent `logical(0)` (was causing an error)
- Made font smaller

**Comment by tmelliott** [comment]
Yep - looks better!
Could you change the display for Excel sheets/rda objects - instead of a comma separator, a bar `|`? It looks a little awkward with the space-comma separation.

**Pull request merged**
