### PR TITLE
update survery obj in summary

### PR DESCRIPTION
**Pull request by chrk623**
#374

### CODE REVIEW

**Comment by tmelliott** [comment]
I'm not sure if this will solve the issue generally - it's only going to work for inference? 

What needs to happen is that, inside the [survey design server](https://github.com/iNZightVIT/Lite/blob/dev/panels/D6_SurveyDesign/2_survey.design.server.R), the survey design object needs to react to `design_params`, which in turn needs to react to `values$data`. 

1. Is that even possible with the current set-up?
2. If not, is there a more global fix (i.e., updating the design when the data is changed, *not* when a component uses it)?

**Comment by chrk623** [comment]
Thought about 1. but I had some doubts, 2. should work though. Let me give it a go.

**Comment by chrk623** [comment]
Still more TODOs:
Currently only works for summary and inference. 

https://github.com/iNZightVIT/Lite/blob/e2f156349a569d409461de40f736d6654b7be468/panels/C1_Visualize/2_visualize-panel-server.R#L7893

Looks OK, dataset in `get.data.set()` and `vis.par()` is updated when the dataset changes i.e., filtered, but the plot is not updating. Figure out why..? Is this the line that plots the data?

**Comment by tmelliott** [comment]
Any updates on this @chrk623 ?  
I'm not sure if this is quite how it should work - but again, limitations of Shiny may be a factor.

The survey design should react to the data.set being changed by any function, rather than trying to re-create the survey object any time it gets used... 
In Desktop, I do this by observing the dataset and, when it changes, checking for the existence of a survey design and if there is one, re-creating the survey object.

Let me know if you need clarification..

**Comment by tmelliott** [comment]
@chrk623 merged, so you can forge ahead with #137 whenever.

**Pull request merged**
